version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
